import "./globals.scss";
import styles from "./color.module.scss";
import Header from "./header/nav";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-primary60">
                <Header />
                {children}
            </body>
        </html>
    );
}
