import "./globals.scss";
import styles from "./color.module.scss";
import Header from "./nav/header";
import fontStyleUtil from "./util/fontStyle";
import Footer from "./nav/footer";
import UseProvider, { UseContext } from "./store/store";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <UseProvider>
                <body className="bg-primary60 ">
                    <Header />
                    {children}
                    <Footer />
                </body>
            </UseProvider>
        </html>
    );
}
