export const metadata = {
    title: "about US",
    description: "Generated by create next app",
};

export default function aboutUsLayout({ children }) {
    return <section>{children}</section>;
}
